# Generated by Django 3.2 on 2021-07-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='is_public'),
        ),
        migrations.AlterField(
            model_name='note',
            name='theme',
            field=models.CharField(default='Без названия', max_length=40, null=True),
        ),
    ]
