# Generated by Django 3.2 on 2021-07-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_system', '0002_auto_20210715_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='theme',
            field=models.CharField(max_length=40),
        ),
    ]
