# Generated by Django 3.2 on 2021-07-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_system', '0006_alter_note_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='theme',
            field=models.CharField(default='Без названия', max_length=40),
        ),
    ]
